sudo: required
services:
  - docker

before_install:
  - docker build -t jsherbin/react-test -f ./client/Dockerfile.dev ./client

scirpt:
  - docker run jsherbin/react-test npm test -- --coverage

after_success:
  - docker build -t jsherbin/multi-client ./client
  - docker build -t jsherbin/multi-nginx ./nginx
  - docker build -t jsherbin/multi-worker ./worker
  - docker build -t jsherbin/multi-server ./server
  #log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push jsherbin/multi-client
  - docker push jsherbin/multi-nginx
  - docker push jsherbin/multi-server
  - docker push jsherbin/multi-worker
